mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
external-controller: '0.0.0.0:9090'
secret: ''
dns:
  enable: true
  ipv6: false
  listen: '0.0.0.0:5353'
  enhanced-mode: redir-host
  nameserver:
    - 'https://223.5.5.5/dns-query'
    - 'https://doh.pub/dns-query'
